// Compatibility layer for legacy screens. Functional icons now share Lucide's
// 24px grid, rounded geometry, and consistent stroke weight.
export {
  ArrowRight,
  BadgeCheck as Verified,
  Bookmark,
  Camera,
  Check as CheckLine,
  CircleCheckBig as CheckBold,
  CircleDollarSign as Dollar,
  Clock3 as Clock,
  Crown,
  DollarSign,
  Dumbbell as Protein,
  Flame,
  Flame as FireIcon,
  Globe2 as Globe,
  Grid2X2 as Grid,
  Heart,
  Leaf,
  Lightbulb as Light,
  MapPin,
  MessageCircle as ChatBubble,
  MessageCircle as Comment,
  ReceiptText as Note,
  Search,
  Settings as Gear,
  Settings as SettingsGear,
  SlidersHorizontal as Filter,
  Sparkles as Sparkle,
  Sprout as Veggie,
  Star,
  Star as StarFilled,
  TrendingUp as Rising,
  Trophy,
  Upload,
  Utensils as Fork,
  UtensilsCrossed as Plate,
  X as Close,
  X as XMark,
} from 'lucide-react'

export {
  BrandMark as HsMark,
  PassIcon as SwipeLeft,
  WantItIcon as ForkFlame,
  WantItIcon as ForkFlameLarge,
  WantItIcon as SwipeRight,
} from '@/app/components/icons/HungerIcons'
